"""empty message

Revision ID: 2ba4c25eb4b5
Revises: 
Create Date: 2023-01-14 16:30:24.935506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba4c25eb4b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_constraint('_follower_followed_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.create_unique_constraint('_follower_followed_uc', ['follower_id', 'followed_id'])

    # ### end Alembic commands ###
