"""empty message

Revision ID: 40deecab32b0
Revises: ba5cca885dae
Create Date: 2023-01-14 18:34:25.667741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40deecab32b0'
down_revision = 'ba5cca885dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_constraint('uq_follow_followed_id', type_='unique')
        batch_op.drop_constraint('uq_follow_follower_id', type_='unique')
        batch_op.create_unique_constraint('unique_constraint_follow', ['follower_id', 'followed_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_constraint('unique_constraint_follow', type_='unique')
        batch_op.create_unique_constraint('uq_follow_follower_id', ['follower_id'])
        batch_op.create_unique_constraint('uq_follow_followed_id', ['followed_id'])

    # ### end Alembic commands ###
