"""empty message

Revision ID: ba5cca885dae
Revises: 2ba4c25eb4b5
Create Date: 2023-01-14 18:32:58.365118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5cca885dae'
down_revision = '2ba4c25eb4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_constraint('uq_follow_followed_id', type_='unique')
        batch_op.drop_constraint('uq_follow_follower_id', type_='unique')
        batch_op.create_unique_constraint('_follower_followed_uc', ['follower_id', 'followed_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_constraint('_follower_followed_uc', type_='unique')
        batch_op.create_unique_constraint('uq_follow_follower_id', ['follower_id'])
        batch_op.create_unique_constraint('uq_follow_followed_id', ['followed_id'])

    # ### end Alembic commands ###
